#!/bin/sh

set -e

[ "$*" ] || exec echo "
Usage: $0 [&|] {start, stop, reload, reload_main (rm), who(w), rr (safe remote restart)}"
trap "echo '
Unexpected Script Error! Use \`/bin/sh -x $0\` to trace it.
'" 0

for p in "$@"
do case "$p" in
start)
# Create the PrivSep empty dir if necessary
[ -d /var/run/sshd ] || {
	mkdir /var/run/sshd
	chmod 0750 /var/run/sshd
}
# dummy
SSHD_OOM_ADJUST=0 /usr/sbin/sshd
# special
cd /etc/ssh
for c in sshd_config+*
do SSHD_OOM_ADJUST=-17 /usr/sbin/sshd -f "/etc/ssh/$c"
done
# show daemons
ps -C sshd -ouid,pid,cmd
;;
reload)
kill -HUP `ps h -C sshd -opid`
;;
reload_main | rm*)
kill -HUP `ps h -C sshd | sed '/+login/s_^\([[:blank:][:digit:]]*\).*_\1_p;d'`
echo 'reload_main'
;;
stop)
# kill daemons, ignoring errors
while ps h -C sshd -opid
do kill -TERM `ps h -C sshd -opid`
   sleep 1
done >/dev/null 2>&1 || :
;;
who | w*)
# show who's running
ps -C sshd -f || :
echo 'who'
;;
rr)
p='remote restart 4 seconds later'
/bin/sh -c 'sleep 4 && /etc/init.d/ssh+ stop start&' >/dev/kmsg 2>&1 <&-
;;
esac
echo "
Results of cmd: '$p'
"
done
trap "" 0
